name: CI

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write  

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t localhost:5000/dummy-node-app:${TAG} app

      - name: Load image into kind cluster
        run: |
          kind load docker-image dummy-node-app:${TAG} --name preview-env

      - name: Update Helm values
        run: |
          sed -i "s|tag:.*|tag: \"${TAG}\"|" helm/dummy-node-app/values.yaml

      - name: Commit Helm change
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add helm/dummy-node-app/values.yaml
          git commit -m "Update image tag to ${TAG}"
          git push
